# Generated by Django 4.1.2 on 2022-12-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('change', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('market_cap', models.BigIntegerField()),
                ('pe_ratio', models.FloatField()),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation', to='myapp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='InsiderTransactions',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insider_transactions', to='myapp.stock')),
            ],
        ),
    ]
